### ISSUE TITLE
.pkg.tar.zst package discontinuation

### ISSUE THREAD

**Issue by etakanaka** [friction2d/friction#148] opened 2024-05-15 00:02 UTC
As a long-time user of enve 2d and a follower of Friction's development, this is my first time commenting. I want to express my gratitude for the team's outstanding work and their valiant efforts in creating the only viable open-source alternative to Adobe After Effects for motion designers.

I noticed that Friction version 9.4 provided a .pkg.tar.zst package. However, with version 9.5 and the roadmap for 1.0.0, there are no mentions of .pkg.tar.zst packaging. I'm curious if it's possible to reintroduce this packaging format or alternatively, add Friction to the AUR.

Your consideration of this matter would be greatly appreciated.

**Comment by rodlie** [comment] 2024-05-15 14:26
Hi

> I noticed that Friction version 9.4 provided a .pkg.tar.zst package

Previous releases had native packages for several distros, they where basically just artifacts after build tests. We have now standardized the build platform and don't need to test on various distros anymore.

From 0.9.6(+) I will only provide a universal build for Linux (provided as an appimage/tarball/rpm), this will be the only supported build on Linux. There are several reasons for this, simplified maintenance, software as intended etc, etc.

> I'm curious if it's possible to reintroduce this packaging format or alternatively, add Friction to the AUR.

No, but feel free to get someone to maintain an unofficial Friction AUR package.

*Note that Friction already is incompatible with Arch, as we need a specific version of FFmpeg to work properly, this will be fixed at some point, but is not a priority.*

**Comment by etakanaka** [comment] 2024-05-15 22:01
thank you very much for the clarification

**Closed** 2024-08-31 11:07 UTC
