### ISSUE TITLE
problem on the scene selector

### ISSUE THREAD

**Issue by irwant** [friction2d/friction#207] opened 2024-07-06 03:42 UTC
this issue about the scene selector not working properly. 
try to make 2 scene  and change the scene on the scene selector canvas. when changed to the scene B, scene on the timeline not changed automatically to scene B because active cursor not on the canvas but on the timeline. check my video attachment. 

https://github.com/friction2d/friction/assets/10395887/84e77289-95b5-4bbd-8c0e-6c6163dc883f

**Comment by irwant** [comment] 2024-07-06 04:13
I don't know this is need to change, because this is important when linking scene A to scene B. and if the link scene A need any change keyframe for quick access, just simple to change scene selector on the timeline or split timeline. I think this is not a big problem, just need a documentation of this feature.

**Comment by rodlie** [comment] 2024-07-06 17:10
The viewer is not "connected" to the timeline in regards to scenes, changing scene in the viewer will not change anything in the timeline, this is because you can have multiple amount of timelines and viewers (you can also have multiple viewers/timelines for one scene).

>  just need a documentation of this feature

Agree, a lot of things need documentation (we don't have any). This is project is mostly maintained and developed by one person in their spare time, so there are limits to what can be done.

**Comment by rodlie** [comment] 2024-08-17 20:56
Will close this, everything works as intended. Can possible be improved or changed in the future, but that's another discussion.

This feature will of course need to be documented #208

**Closed by rodlie** 2024-08-17 20:56 UTC
