### ISSUE TITLE
Graphic curves are broken when scaling

### ISSUE THREAD

**Issue by eFe-Munoz** [friction2d/friction#258] opened 2024-10-08 15:28 UTC
![image](https://github.com/user-attachments/assets/40947c74-100f-4b8d-8ab6-0740ada83a9a)

As in previous versions, being in Timeline (no matter Graph mode on off) the graphic curves are broken when scaling them.

Process:
1.- In Graph mode (looks better) you select at least 2 keyframes. 
2.- Place the cursor at the origin of the scaling (usually at the beginning of the animation (frame zero).
3.- Press “S” and scale.

![image](https://github.com/user-attachments/assets/c82399aa-cd16-4734-907d-69bb4f3d706b)

4.- As you can see in image 2, the link between keyframe 1 and 2 is broken (and affects the animation).

![image](https://github.com/user-attachments/assets/89c27b18-8e4e-47a8-afa2-87025de44014)

This scaling system is very important because it allows to scale one or several animated elements at the same time, that is to say, to scale animation speeds proportionally.

**Comment by rodlie** [comment] 2024-10-08 15:52
This has been discussed before, don't remember the issue.

Anyway, this seems to happen in some circumstances, some calculation somewhere(?)

A quick test works for me (very limited, probably not enough to trigger the issue)


https://github.com/user-attachments/assets/5d99347b-71b1-4098-9f1b-4cc3a45bdd5d


https://github.com/user-attachments/assets/69820a35-2d5b-4f09-bcea-c8dee420c5f0

**Comment by rodlie** [comment] 2024-10-08 15:53
Yeah.... it's related to smooth nodes:


https://github.com/user-attachments/assets/81de6593-6922-40e6-bbbb-0c5ff84934f6

**Comment by rodlie** [comment] 2024-10-08 16:07
close, duplicate of #210 (continue there).

**Closed by rodlie** 2024-10-08 16:07 UTC
Labels: bug, graph
