### ISSUE TITLE
Can't commpile with ffmpeg 7.1

### ISSUE THREAD

**Issue by AlexanderShad** [friction2d/friction#369] opened 2024-12-14 10:28 UTC
Hello

I can't commpile friction with ffmpeg 7.1

```
/usr/src/RPM/BUILD/friction-0.9.6.1/src/core/CacheHandlers/samples.h:67:20:
 error: use of undeclared identifier 'av_get_channel_layout_nb_channels'
   67 | fNChannels(av_get_channel_layout_nb_channels(channelLayout)),

----

/usr/src/RPM/BUILD/friction-0.9.6.1/src/core/FileCacheHandlers/../Sound/esoundsettings.h:51:16: error: use of undeclared identifier 'av_get_channel_layout_nb_channels'
   51 |         return av_get_channel_layout_nb_channels(fChannelLayout);
      |                ^
3 errors generated.
gmake[2]: *** [src/core/CMakeFiles/frictioncore.dir/build.make:378: src/core/CMakeFiles/frictioncore.dir/Animators/outlinesettingsanimator.cpp.o] Error 1

```

In ffmpeg 7.1 not av_get_channel_layout_nb_channels 

OS: ALT Linux Sisyphus

**Comment by rodlie** [comment] 2024-12-15 14:53
Duplicate of #135

**Closed by rodlie** 2024-12-15 14:53 UTC
