### ISSUE TITLE
Theme changes

### ISSUE THREAD

**Issue by adambelis** [friction2d/friction#155] opened 2024-05-23 13:53 UTC
![image](https://github.com/friction2d/friction/assets/50795097/e02ce860-b493-4cb7-a883-d7d315144679)
 current proposed 
 also would add padding next to icons

**Comment by rodlie** [comment] 2024-05-23 14:01
Sure, but this need more planning as everything uses the same style. We don't want to just style the fill/stroke buttons, then they don't fit in with the rest of the app.

Suggestions (with colors alternatives) are welcome.

Our current stylesheet: https://github.com/friction2d/friction/blob/main/src/app/friction.qss

Primary colors we now use:
```
    palette.setColor(QPalette::Window, QColor(40, 40, 47));
    palette.setColor(QPalette::WindowText, Qt::white);
    palette.setColor(QPalette::Base, QColor(33, 33, 38));
    palette.setColor(QPalette::AlternateBase, QColor(40, 40, 47));
    palette.setColor(QPalette::Link, Qt::white);
    palette.setColor(QPalette::LinkVisited, Qt::white);
    palette.setColor(QPalette::ToolTipText, Qt::white);
    palette.setColor(QPalette::ToolTipBase, Qt::black);
    palette.setColor(QPalette::Text, Qt::white);
    palette.setColor(QPalette::Button, QColor(33, 33, 38));
    palette.setColor(QPalette::ButtonText, Qt::white);
    palette.setColor(QPalette::BrightText, Qt::red);
    palette.setColor(QPalette::Highlight, QColor(177, 16, 20));
    palette.setColor(QPalette::HighlightedText, Qt::white);
    palette.setColor(QPalette::Disabled, QPalette::Text, Qt::darkGray);
    palette.setColor(QPalette::Disabled, QPalette::ButtonText, Qt::darkGray);
```

**Comment by rodlie** [comment] 2024-05-23 16:17
quick-and-dirty css mod:

https://github.com/friction2d/friction/assets/34516798/78cb10aa-ba31-4d0e-84d0-77a6edfc7ba3

Would also need to adjust the base color, since we now have a bit too much contract. Anyway, just wanted to show how it would look "for real".

**Comment by adambelis** [comment] 2024-05-23 16:51
yes this already looks much better  need more tweaking but nice

**Comment by rodlie** [comment] 2024-05-25 15:22
Started refactoring the code related to theme/colors, this issue was a good excuse to start removing hardcoded stuff everywhere in the code.

Very WIP screenshot (nothing is final and will be easy to modify after refactor):
![theme-wip-001](https://github.com/friction2d/friction/assets/34516798/9a6379b6-4a40-498c-b5f2-d716d701796e)


Also, a very annoying thing in Qt is that if I modify something like a border color through CSS I then need to re-implement the complete style for that widget (modify something and you clear the default css).

*"I Just need to change a hover color, easy! Changes color and the widget looses all styling and you waste an hour adding it back..."*

**Comment by adambelis** [comment] 2024-05-25 15:48
i saw som qt utility tools  for styling maybe that would help ? (no idea)
https://doc.qt.io/GammaRay/gammaray-widget-inspector.html
https://doc.qt.io/GammaRay/gammaray-tools.html

**Comment by rodlie** [comment] 2024-05-25 15:53
> i saw som qt utility tools for styling maybe that would help ?

I have no issues with doing the styling. But we use the Qt style "fusion" as our base, the problem is that if we override it through CSS then we need to re-implement what "fusion" did. Basically I need to write a complete CSS for the app, not just add minor changes to the "fusion" base. No biggie, just takes extra time.

**Comment by adambelis** [comment] 2024-05-25 15:56
ah in gtk  this is possible to over with just spesific style (sometime :D).

**Comment by adambelis** [comment] 2024-05-25 16:13
btw imho OBS has very nice theme if you alos want to try that as a base https://obsproject.com/forum/resources/yami-resized.1611/updates

**Comment by rodlie** [comment] 2024-10-05 12:45
The majority of changes has been made, there might be some minor tweaks needed, but we can always adjust in future releases. Closing.

**Closed by rodlie** 2024-10-05 12:45 UTC
Labels: enhancement, in progress, qt, ui
